package com.utils;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.net.URL;
import java.nio.charset.Charset;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.concurrent.Exchanger;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Created by rjaraja on 7/18/16.
 */
public class Pin {

    private static String readAll(Reader rd) throws IOException {
        StringBuilder sb = new StringBuilder();
        int cp;
        while ((cp = rd.read()) != -1) {
            sb.append((char) cp);
        }
        return sb.toString();
    }

    public static JSONObject readJsonFromUrl(String url) throws IOException, JSONException {
        InputStream is = new URL(url).openStream();
        try {
            BufferedReader rd = new BufferedReader(new InputStreamReader(is, Charset.forName("UTF-8")));
            String jsonText = readAll(rd);
            JSONObject json = new JSONObject(jsonText);
            return json;
        } finally {
            is.close();
        }
    }

    public static void main(String[] args) throws IOException, JSONException {
        String[] boardUrls = new String[]{
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/gray/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/spring-2015-trends/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/paint-color/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/gardens/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/outdoor-paint-color/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/art-I-love/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/photography/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/posters/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Rugs/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/light-fixtures/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/outdoor-rooms/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/love-this-photo!/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/inspiration-boards/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/kitchens/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/flowers/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Lofts/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/architecture/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/great-rooms/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/fashion/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/We-love-green!/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Fun-at-the-flea-market/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/White/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Galleries/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Decorating-with-books/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Pillows/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/kids-rooms/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Great-chairs/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Products-I-like/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/our-new-house/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/bathrooms/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Crazy-Colors/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Visual-Jill:-ideas-we-can-use/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Joey-kitchen-ideas/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Judith-Petersen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/indigo-and-denim/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/light-fixtures/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/JP-phase-2/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Sullivan-office-art/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/glamorous/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/winter/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/bedrooms/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/new-office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/black-and-white/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/outdoor-chairs/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/CC/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Living-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Living-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Bedroom-2/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Bedroom-1/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Front-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Exterior-entrance/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Pinecrest/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SH-inspiration/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/U-B-finishing-touches/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/entrance-way/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Jill's-new-house/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Shelly-G/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Ethan-C/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/JA/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Gayle-T/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Anne-Ryan/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Eric-Elena/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Gayle-T-Adam/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Rachel-T/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Susan-H/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Gayle-T-Grace/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Gayle-T-Issac-Noah/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Nancy-F/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Nancy-F-Bath/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Carol-M/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Sarah-S/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Sarah-S-Living-RoomDining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Vicki-B/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/S-J-Breakfast-Nook/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/S-J-Living-Room-Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/S-J-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/R-and-D/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/neutrals/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Gayle-T-Master/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/S-J-Zen-Office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Vicki-Mike-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/D-S/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Ann-L/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Ann-L-Formal-Living/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/A-A/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/BI/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/JK/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/2015-favorite-paint-colors/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/JS/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/RA-Living-Dining/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/RA-Craft-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/RA-Family-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Blue/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Susan-bathroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/ceramics/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/ST/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/M's-attic/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/R-G/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Debbie-L/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/laura/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SL-Living-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SL-Baby's-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SH-Living-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Amy-D/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/L-K-PAINT-COLORS/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/L-K-KITCHEN/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/L-K-DINING-ROOM/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/L-K-LIVING-ROOM/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/offices/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SH-Kitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SH-Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SH-Master-Bath/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/A-S-Family-RoomKitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/A-S-Living-RoomDining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/A-S-Paint-colors/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SH-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SH-Kitchen-Seating-Nook/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/L-K-Laundry/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/CB/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/T-L-Entry-Family-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/T-L-Living-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/T-L-OfficeReading-RoomPatio/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/T-L-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/T-L-Rooftop-Living/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/J-Z-Guest-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/JZ-Living-RoomDining-RoomOffice/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/A-S-Lighting/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/VO-DECK/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/VO-KITCHENFAMILY-ROOM/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/VO-LIVING-ROOM/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/bright-color-with-neutrals/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/L-K-Guest-Bedroom-2/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/L-K-Guest-Bedroom-1Office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/L-K-Master-Bathroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Ann-L-Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/HR-Office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SP-Lily's-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/M-M-Kid's-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Tile/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/neutrals-and-naturals/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/ways-with-wood/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Lyons/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/montclair-modern/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Charity/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/RL-Abby/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/RL-Office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/NS-Kitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/NS-Bathrooms/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/NS-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/NS-Bedroom-1-SMALL/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/NS-Bedroom-2/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/NS-Bedroom-3-(kitchenette)/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/NS-Outdoor-Living/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/NS-Living-RoomDining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/NS-art/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/JUL/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/L-P-fireplace/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/A-S-Half-Bath/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/KR-Living-RoomKitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/KR-Reading-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/PR-Playroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/PR-Living-RoomEntry/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/IW-Paint-Colors/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/IG-Living-RoomDining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/IW-BedroomBathroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/IW-Living-RoomDining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SH-office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/R-G-Bathroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/R-K-Office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/M-Bathroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/HB/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/GM-Paint-colors/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/GM-Living-Room-Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/GM-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/GM-Guest-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/VO-Master-Bedroom-Guest-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/VO-Guest-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SP-Master/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/S-T-inspiration/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/J-T-Living-RoomDining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/J-T-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/J-T-Bath-materials/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/J-T-Exterior/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/J-T-Office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/JY-Family-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/JY-Guest-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/G-M-Living-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/G-M-Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/G-M-Kitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/G-M-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/G-M-Guest-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/JY-Living-RoomDining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/JY-Guest-Bathroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/GE-Kitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Nina-G/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/new-hardware/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Sarah-L-Family-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Sarah-L-Aidan's-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/DL-Living-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/DL-Guest-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/DL-Outdoor-Garage-Apartment/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/K-D-Den/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/K-D-Playroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/DL-Master-Bedroom-Bathroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/AMY-D-BATH/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Katy-B-Playroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Katy-B-Boys'-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Judy-P-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Judy-P-OfficeGuest-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/E-E-INSPIRATION/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Katy-B-Desk-area/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Judy-P-Extras/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/R-G-Living-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Susan-Living-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/B-M-Living-roomdining-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/B-M-GUEST-ROOM/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/B-M-Master-bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/B-M-Bathroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Susan-H-Entryway/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Susan-Kitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Susan-Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Susan-Back-Sitting-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Pam-Kitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Pam-Bathrooms/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/BH-Living-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/BH-OfficeGuest-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/BH-Kitchen-and-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/BH-Patio/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/L-Project/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MLee-Master-Bath/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MLee-Upstairs-Bath/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MLee-Half-Bath/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MLee-Living-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Julia-T-Paint-colors/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SH-outdoor/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MLee-Dining-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/2016-colors/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Anja-Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MLee-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Anja-Living-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Anja-Family-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Anja-Bedroom-1-Master/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Anja-Bedroom-2/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Anja-Bedroom-3/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Anja-Bedroom-4/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Anja-Bedroom-5Attic/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Anja-Attic-Living-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Anja-Small-deck-outside-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Julia-T-Lighting/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/AC-Living-roomdining-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Anja-Attic-Nook/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/SG-MASTER-BEDROOM/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/JW/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Susan-Aly's-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Susan-David's-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Susan-Powder-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/F-M-Living-Room-Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/F-M-Family-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Marisa-M/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/R-D-Master/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/R-D-Office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/T-C-Entry/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/T-C-Living,-Dining,-Kitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/T-C-GuestOffice/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/T-C-Master-Bedroom-Bath/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/T-C-Patio/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Monty-C-Bath/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Bora-H/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/F-A-Gabe's-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/F-A-Front-LR/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/F-A-Sitting-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/F-A-Family-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/F-A-Master/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/F-A-Office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/C-D-Living-RoomDining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/C-D-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/C-D-Office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/C-D-Bathrooms/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/C-D-Upstairs-Den/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/C-D-Guest-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/WJ-Living-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/WJ-Dining-Room-Kitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/WJ-Master-BedroomBathroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/VC-Living-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/VC-Family-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/VC-Guest-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/VC-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/2016-inspiration/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/NA-Living-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/NA-Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Sayaka-Ideas/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/CB-Living-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MS-Bath-1-Master-Bath/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/CB-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/CB-Dining-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Janice-H-Design/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MS-Paint-Colors-Carpet/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MS-Living-Room-KitchenDining/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MS-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/J-R-Bathroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Amira-Kiddos-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Shasa-Paint-colors/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Jen-Landscape-Design/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Shasa-Flooring/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Daralyn-Design-Boost/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Jen-H-Living-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Jen-H-Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Jen-H-Kitchen-Kitchen-Nook/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Jen-H-Media-Den/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Jen-H-Bathroom-Design/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Sandra-Design-Boost/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Robin-L-Living-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/A-M-DINING-ROOM-FORMAL-SEATING-AREA/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/A-M-KITCHEN-BUFFET-AREA/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/A-M-FAMILY-ROOM/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/A-M-OUTDOOR-LIVING/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/A-M-ENTRY/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/A-M-MASTER-BEDROOM/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MR-Living-Room-Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MR-Kitchen-Entry/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MR-Lady-Cave/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/TG-Living-RoomDining-RoomKitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/TG-Master-Bedroom-Bathroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/C-D-Stair-pendant-Outdoor-furniture/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/H-Z-Living-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/H-Z-Dining-Room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/H-Z-Office/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/H-Z-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/H-Z-Kitchen-Laundry/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Jen-Furnishings/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/Jen-Paint/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/M-B-Price-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/LS-living-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/LS-family-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/LS-master-bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/LS-guest-bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/M-B-Price-Outdoor-living-area/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/DP-Living-roomdining-roomkitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/DP-Master-bedroom-bathroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/DP-LoftLiving-room-exterior-deck/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/MJ-Paint/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/L-K-Master-bath/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/L-K-Master-bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/C-C-Living-+-Dining/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/M-A-Living-roomdining-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/M-A-Master-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/M-A-Upstairs-Family-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/DWR-Living-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/DWR-color-stories/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/DWR-Dining-room/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/DWR-Bedroom/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/M-Lee-Kitchen/pins/",
                "http://api.pinterest.com/v3/pidgets/boards/visualjill/living-room/pins/"
        };

        for (String boardUrl : boardUrls) {
            try {

                JSONObject json = readJsonFromUrl(boardUrl);
//            JSONObject json = readJsonFromUrl("http://widgets.pinterest.com/v3/pidgets/users/firuzehm/pins?limit=200");
//        JSONObject json = readJsonFromUrl("http://widgets.pinterest.com/v3/pidgets/users/firuzehm/pins/");
//        System.out.println(json.toString());
                JSONObject data = (JSONObject) json.get("data");

                JSONObject dataBoard = (JSONObject) data.get("board");
                String boardName = (String) dataBoard.get("name");

                JSONArray pins = (JSONArray) data.get("pins");
                HashMap<String, HashSet<String>> urls = new HashMap<>();
//                System.out.println("Pin count - " + pins.length());
                for (int i = 0; i < pins.length(); i++) {
                    JSONObject o = (JSONObject) pins.get(i);
                    String domain = (String) o.get("domain");
//                    JSONObject board = (JSONObject) o.get("board");
//                    String name = (String) board.get("name");

                    HashSet<String> strings = urls.get(boardName);
                    if (strings == null) {
                        strings = new HashSet<>();
                        urls.put(boardName, strings);
                    }
                    strings.add("http://" + domain);
                }
                for (Map.Entry url : urls.entrySet()) {
                    System.out.println(url.getKey() + " - " + url.getValue());
                }
            } catch (Exception e) {

            }
        }
    }
}
